#version: '3.8'

services:

  db:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    build: ./airflow_dags
    restart: always
    env_file: .env
    volumes:
      - ./airflow_dags:/app
    depends_on:
      - db
    ports:
      - "8080:8080"

  fastapi:
    build: ./API_WebScr
    restart: always
    env_file: .env
    volumes:
      - ./API_WebScr:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  pyspark:
    build: ./PySpark
    env_file: .env
    volumes:
      - ./PySpark:/app
    depends_on:
      - db

  dwh:
    build: ./DWHmodelling
    env_file: .env
    volumes:
      - ./DWHmodelling:/app
    depends_on:
      - db

volumes:
  postgres_data:


